### ISSUE TITLE
Not compatible with Scala 2.12

### ISSUE THREAD

**Issue by ashamshad** [pragmatico/swagger-ui-akka-http#2]
My project is on Scala 2.12, I tried to include this library in my dependencies but it is not compatible with Scala 2.12

`[warn] 	Note: Unresolved dependencies path:
[warn] 		co.pragmati:swagger-ui-akka-http_2.12:1.0.0`

**Comment by jmbataller** [comment]
Thanks for your changes, they have been merged and released.
